image: python:latest

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

shed:
    stage: Static Analysis
    script:
        - shed --refactor
    tags:
        - ci

flake8:
    stage: Static Analysis
    script:
        - flake8 --ignore=E501,W391,W503
    tags:
        - ci

mypy:
    stage: Static Analysis
    allow_failure: true
    script:
        - mypy lightning_pass --ignore-missing-imports
    tags:
        - ci

pytest:
    stage: Test
    script:
        - pytest -s --no-qt-log
    tags:
        - ci
