image: python:latest

before_script:
    - python3 -V
    - sudo apt-get install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev
    - wget -O /tmp/Python-3.9.1.tar.xz https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
    - cd /tmp
    - tar xf Python-3.9.1.tar.xz
    - cd Python-3.9.1
    - ./configure-3.9.1
    - sudo make altinstall
    - sudo apt -y autoremove
    - cd
    - rm -rf /tmp/Python-3.9.1
    - rm /tmp/Python-3.9.1.tar.xz
    - sudo ln -s /usr/local/bin/python3.9 /usr/bin/python3.9
    - echo "alias python=/usr/local/bin/python3.9" >> ~/.bashrc
    - echo "alias python3=/usr/local/bin/python3.9" >> ~/.bashrc
    - source ~/.bashrc
    - cd ..
    - . ~/.bashrc
    - python3 -V
    - python3 -m pip install -r requirements.txt

stages:
    - build
    - static analysis
    - test

black:
    stage: static analysis
    script:
        - black --check .
    tags:
        - ci

flake8:
    stage: static analysis
    script:
        - flake8 --ignore=E501,W391,W503,D100,D104
    tags:
        - ci

pydocstyle:
    stage: static analysis
    script:
        - pydocstyle
    tags:
        - ci

pylama:
    stage: static analysis
    script:
        - pylama -i W391,E501
    tags:
        - ci

pylint:
    stage: static analysis
    script:
        - pylint --disable=W0201,I1101,E0611,C0301 lightning_pass --ignore main.py
    tags:
        - ci

mypy:
    stage: static analysis
    script:
        - mypy lightning_pass --ignore-missing-imports
    tags:
        - ci

pytest:
    stage: test
    script:
        - pytest -s --no-qt-log
    tags:
        - ci
