image: python:latest

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

shed:
    stage: Static Analysis
    script:
        - shed --refactor
    tags:
        - ci

flake8:
    stage: Static Analysis
    script:
        - flake8 --ignore=E501,W391,W503
    tags:
        - ci

mypy:
    stage: Static Analysis
    allow_failure: true
    script:
        - mypy lightning_pass --ignore-missing-imports
    tags:
        - ci

pytest:
    stage: Test
    before_script:
        - apt-get update
        - apt-get install ffmpeg libsm6 libxext6  -y
        - apt-get install -y xvfb herbstluftwm
        - apt-get install libxkbcommon-x11-0 -y

        - QT_DEBUG_PLUGINS=1
        - mkdir /usr/bin/platforms
         - ln -s /our/local/libqxcb.so /usr/bin/platforms/libqxcb.so
    script:
        - "herbstluftwm &"
        - pytest -s --no-qt-log
    tags:
        - ci
