image: python:latest

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

shed:
    stage: Static Analysis
    script:
        - shed

flake8:
    stage: Static Analysis
    script:
        - flake8 --ignore=E501,W391,W503

mypy:
    stage: Static Analysis
    allow_failure: true
    script:
        - mypy lightning_pass --ignore-missing-imports

pytest:
    stage: Test
    script:
        - RUN apt-get update
        - RUN apt-get install ffmpeg libsm6 libxext6  -y
        - pytest
