image: python:latest

before_script:
    - curl https://bootstrap.pypa.io/get-pip.py | python3
    - apt-get upgrade && apt-get upgrade python3-pip
    - apt-get upgrade python3-pip python3-setuptools python3-psutil python3-bottle python3-requests
    - apt install python-dev -y
    - python3 -V
    - python3 -m pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

black:
    stage: Static Analysis
    script:
        - black --check .
    tags:
        - ci

flake8:
    stage: Static Analysis
    script:
        - flake8 --ignore=E501,W391,W503,D100,D104
    tags:
        - ci

pydocstyle:
    stage: Static Analysis
    script:
        - pydocstyle
    tags:
        - ci

pylama:
    stage: Static Analysis
    script:
        - pylama -i W391,E501
    tags:
        - ci

pylint:
    stage: Static Analysis
    script:
        - pylint --disable=W0201,I1101,E0611,C0301 lightning_pass --ignore main.py
    tags:
        - ci

mypy:
    stage: Static Analysis
    script:
        - mypy lightning_pass --ignore-missing-imports
    tags:
        - ci

pytest:
    stage: Test
    script:
        - pytest -s --no-qt-log
    tags:
        - ci
