image: python:latest

before_script:
    - apt-get update
    - apt-get install ffmpeg libsm6 libxext6  -y
    - apt-get install -y xvfb herbstluftwm

    - QT_DEBUG_PLUGINS=1
    - mkdir /usr/bin/platforms
    - ln -s /our/local/libqxcb.so /usr/bin/platforms/libqxcb.so

    - python --version
    - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

shed:
    stage: Static Analysis
    script:
        - shed --refactor

flake8:
    stage: Static Analysis
    script:
        - flake8 --ignore=E501,W391,W503

mypy:
    stage: Static Analysis
    allow_failure: true
    script:
        - mypy lightning_pass --ignore-missing-imports

pytest:
    stage: Test
    script:
        - pytest -s --no-qt-log
