image: python:latest

stages:
    - build
    - static Analysis
    - test

build:
    stage: build
    script:
        - docker build . - t app
    tags:
        - ci

black:
    stage: static Analysis
    script:
        - black --check .
    tags:
        - ci

flake8:
    stage: static Analysis
    script:
        - flake8 --ignore=E501,W391,W503,D100,D104
    tags:
        - ci

pydocstyle:
    stage: static Analysis
    script:
        - pydocstyle
    tags:
        - ci

pylama:
    stage: static Analysis
    script:
        - pylama -i W391,E501
    tags:
        - ci

pylint:
    stage: static Analysis
    script:
        - pylint --disable=W0201,I1101,E0611,C0301 lightning_pass --ignore main.py
    tags:
        - ci

mypy:
    stage: static Analysis
    script:
        - mypy lightning_pass --ignore-missing-imports
    tags:
        - ci

pytest:
    stage: test
    script:
        - pytest -s --no-qt-log
    tags:
        - ci
