image: python:latest

before_script:
    - python3 --version
    - python3 -m pip install -r requirements.txt

stages:
    - build
    - static analysis
    - test

black:
    stage: static analysis
    script:
        - black --check .
    tags:
        - ci

flake8:
    stage: static analysis
    script:
        - flake8 --ignore=E501,W391,W503,D100,D104
    tags:
        - ci

pydocstyle:
    stage: static analysis
    script:
        - pydocstyle
    tags:
        - ci

pylama:
    stage: static analysis
    script:
        - pylama -i W391,E501
    tags:
        - ci

pylint:
    stage: static analysis
    script:
        - pylint --disable=W0201,I1101,E0611,C0301 lightning_pass --ignore main.py
    tags:
        - ci

mypy:
    stage: static analysis
    script:
        - mypy lightning_pass --ignore-missing-imports
    tags:
        - ci

pytest:
    stage: test
    script:
        - pytest -s --no-qt-log
    tags:
        - ci
