image: python:latest

before_script:
    - python --version

stages:
    - build
    - test

build:
    stage: build
    script:
        - python -m pip install poetry
        - poetry install
    tags:
        - ci

pytest:
    stage: test
    script:
        - pytest -s --no-qt-log
    tags:
        - ci
