image: python:latest

before_script:
    - python --version

stages:
    - build
    - test

build:
    stage: build
    script:
        - python -m pip install --upgrade pip
        - python -m pip install poetry
        - poetry --version
        - poetry config virtualenvs.in-projects true
        - poetry install --no-interaction --no-ansi
    tags:
        - ci

pytest:
    stage: test
    script:
        - poetry run pytest -s --no-qt-log
    tags:
        - ci
